### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by sanek1000804** [vatsimnetwork/simaware-tracon-project#152]
In Russia there is specific control position - Radar. It is like small approach, usually having a shape of circle. Radar's suffix is R_APP. How can I make it so that when the Radar is connected, the approach boundary is not shown? If needed, I can make all R_APP boundaries, but will the simaware distinguish them and, when connecting the Radar, show exactly its zone? Please, help me by telling me how to do it right. Thanks,

**Comment by maiuswong** [comment]
Hi there, I guess I'm not sure I understand your question.  So let me answer two questions:

1. If your goal is to make it so that no approach boundary is shown at all, then that is not possible.  SimAware doesn't have a way to suppress a boundary when given a R_APP prefix (and that's likely to conflict with other facilities; MSP_R_APP, for example, is a frequently-used radar sector).
2. If your goal is to make R_APP for each boundary in Russia, yes that is possible.  Your prefix in this case would be "UUEE_R", for example.

**Comment by sanek1000804** [comment]
Hi. Thank for fast response! Of course, I'm not going to make R_APP for all Russia airports, just for airports of my FIRs. So, all in all, if I will make two boundaries with prefixes "USSS" and "USSS_R", will SimAware distinguish them?

**Comment by sanek1000804** [comment]
Yes, that works.
