### ISSUE TITLE
Multiple positions appear to be either Towers or Procedural Towers

### ISSUE THREAD

**Issue by dirtyformal** [vatsimnetwork/simaware-tracon-project#192]
In the dataset there are a handful of positions that appear to be either Tower positions, or Procedural Tower positions. In line with this project, only TRACON/Terminal units are intended to be used within this dataset. This will warrant further investigation and discussion - needing to decide whether or not we include Procedural Towers into the Dataset.

https://github.com/vatsimnetwork/simaware-tracon-project/blob/ba1e1fdba64cc327221877eb0566cbc3383bc13c/TRACONBoundaries.geojson?short_path=2074183#L136-L137
https://github.com/vatsimnetwork/simaware-tracon-project/blob/ba1e1fdba64cc327221877eb0566cbc3383bc13c/TRACONBoundaries.geojson?short_path=2074183#L145-L146
https://github.com/vatsimnetwork/simaware-tracon-project/blob/ba1e1fdba64cc327221877eb0566cbc3383bc13c/TRACONBoundaries.geojson?short_path=2074183#L463
https://github.com/vatsimnetwork/simaware-tracon-project/blob/ba1e1fdba64cc327221877eb0566cbc3383bc13c/TRACONBoundaries.geojson?short_path=2074183#L468

**Comment by Adrian2k** [comment]
ENAN, ENAT, ENKR and ENNA is _APP possitions. Ie ENAN_APP, ENAT_APP etc, covering their respective TMA's.
They are also defined as approach positions in the AIP, however with the callsign "Tower".

They function just like any other TMA's in Norway, it is just some few cases where the callsign is "Tower" instead of "Approach".

![image](https://user-images.githubusercontent.com/35482228/191016762-9ddf559b-f7b0-48dd-b14b-9ab79c08b40a.png)
