### ISSUE TITLE
Incorrect Airport displayed for ML_TWR login

### ISSUE THREAD

**Issue by vatpacais** [vatsimnetwork/simaware-tracon-project#232]
When ML_TWR is logged in, YSML is shown as the Tower airport instead of YMML. The ATIS is shown as YMML which is correct

**Comment by psvatpac** [comment]
I noticed the same is happening for AD_TWR which appears as YSAD instead of YPAD. I assume these are coming from vatspy data. In that case the line YMML|Melbourne|-37.673333|144.843333|ML|YELW|0 should be used for ML_ logins with the 5th item being the login prefix for the airport. Where there is a blank 5th item, no Tower exists. The 5th item is an alias for the ICAO that is used for ATC callsigns - hope that makes sense

**Comment by kmoberg** [comment]
@vatpacais @psvatpac This needs to be reported directly to Simaware to figure out how the application parses logon callsigns to airports. This repo is just for the TMA/TRACON data.

CC @maiuswong

**Comment by maiuswong** [comment]
Thanks @kmoberg, I have pushed an update to SimAware which should resolve this issue.  @vatpascais @psvatpac please open a ticket in [maiuswong/simaware-express](https://github.com/maiuswong/simaware-express) if the issue persists.
